Repository edu-pi/Backend-User-Server, pull requests merged in 2024-09, with the labels that each got.

#28 [#27]feat: CORS 적용을 위한 WebConfig 추가
  src/main/java/soma/haeya/edupi_user/config/WebConfig.java
Labels: BE

#30 [#29]deploy: cicd 도입
  .github/workflows/cicd-dev.yml
  .github/workflows/pull-request-build.yml
  .gitignore
  edupi_user.json
  src/main/java/soma/haeya/edupi_user/client/MemberApiClient.java
  src/main/java/soma/haeya/edupi_user/controller/HealthCheckController.java
  src/main/resources/.gitkeep
Labels: BE, deploy

#24 [#23]feat: swagger 코드 추가
  .DS_Store
  build.gradle
  src/main/java/soma/haeya/edupi_user/config/SwaggerConfig.java
  src/main/java/soma/haeya/edupi_user/controller/MemberController.java
  src/main/java/soma/haeya/edupi_user/service/MemberService.java
Labels: BE

#31 [#26]Refactor: 회원가입 에러코드 변경
  src/main/java/soma/haeya/edupi_user/GlobalExceptionHandler.java
  src/main/java/soma/haeya/edupi_user/client/MemberApiClient.java
  src/main/java/soma/haeya/edupi_user/client/config/MemberApiRestClientConfig.java
  src/main/java/soma/haeya/edupi_user/controller/MemberController.java
  src/main/java/soma/haeya/edupi_user/dto/request/SignupRequest.java
  src/main/java/soma/haeya/edupi_user/dto/response/ErrorResponse.java
  src/main/java/soma/haeya/edupi_user/dto/response/Response.java
  src/main/java/soma/haeya/edupi_user/dto/response/SignupResponse.java
  src/main/java/soma/haeya/edupi_user/exception/DbValidException.java
  src/main/java/soma/haeya/edupi_user/exception/GlobalExceptionHandler.java
  src/main/java/soma/haeya/edupi_user/exception/InnerServerException.java
  src/main/java/soma/haeya/edupi_user/exception/UnexpectedServerException.java
  src/main/java/soma/haeya/edupi_user/service/MemberService.java
  src/test/java/soma/haeya/edupi_user/client/MemberApiClientTest.java
  src/test/java/soma/haeya/edupi_user/controller/MemberControllerTest.java
  src/test/java/soma/haeya/edupi_user/dto/request/SignupRequestTest.java
  src/test/java/soma/haeya/edupi_user/service/MemberServiceTest.java
Labels: BE

#34 [#33]feat: Swagger 통합위해 설정 변경
  build.gradle
  src/main/java/soma/haeya/edupi_user/config/OpenApiConfig.java
  src/main/java/soma/haeya/edupi_user/controller/HealthCheckController.java
  src/main/java/soma/haeya/edupi_user/controller/MemberController.java
  src/main/java/soma/haeya/edupi_user/controller/MemberSpecification.java
  src/test/java/soma/haeya/edupi_user/controller/MemberControllerTest.java
Labels: BE

#40 [#36]feat: 이메일 인증 메일 보내기 + 검증
  build.gradle
  src/main/java/soma/edupi/user/EdupiUserApplication.java
  src/main/java/soma/edupi/user/client/MemberApiClient.java
  src/main/java/soma/edupi/user/config/EmailConfig.java
  src/main/java/soma/edupi/user/controller/MemberController.java
  src/main/java/soma/edupi/user/controller/MemberSpecification.java
  src/main/java/soma/edupi/user/dto/request/EmailRequest.java
  src/main/java/soma/edupi/user/dto/request/MemberLoginRequest.java
  src/main/java/soma/edupi/user/dto/request/SignupRequest.java
  src/main/java/soma/edupi/user/service/EmailService.java
  src/main/java/soma/edupi/user/service/MemberService.java
  src/main/resources/templates/mail.html
  src/test/java/soma/edupi/user/controller/MemberControllerTest.java
  src/test/java/soma/edupi/user/service/MemberServiceTest.java
Labels: feat, BE
