Repository edu-pi/Backend-User-Server, pull requests merged in 2024-08, with the labels that each got.

#11 [#9]feat: 회원가입 form 데이터 검증(Re)
  build.gradle
  src/main/java/soma/haeya/edupi_user/EdupiUserApplication.java
  src/main/java/soma/haeya/edupi_user/signup/SignUpController.java
  src/main/java/soma/haeya/edupi_user/signup/SignUpExceptionHandler.java
  src/main/java/soma/haeya/edupi_user/signup/dto/request/SignupRequest.java
  src/main/java/soma/haeya/edupi_user/signup/dto/response/ErrorResponse.java
  src/main/java/soma/haeya/edupi_user/signup/dto/response/SuccessResponse.java
  src/main/java/soma/haeya/edupi_user/signup/exception/DbValidException.java
  src/test/java/soma/haeya/edupi_user/signup/SignUpControllerTest.java
  src/test/java/soma/haeya/edupi_user/signup/dto/SignupRequestTest.java
Labels: feat, BE

#12 [#7]feat: 로그인 기능 구현 token 발급, token 정보 확인
  build.gradle
  src/main/java/soma/haeya/edupi_user/login/auth/TokenProvider.java
  src/main/java/soma/haeya/edupi_user/login/client/MemberApiClient.java
  src/main/java/soma/haeya/edupi_user/login/client/config/MemberApiRestClientConfig.java
  src/main/java/soma/haeya/edupi_user/login/controller/MemberController.java
  src/main/java/soma/haeya/edupi_user/login/domain/Member.java
  src/main/java/soma/haeya/edupi_user/login/domain/Role.java
  src/main/java/soma/haeya/edupi_user/login/dto/MemberLoginRequest.java
  src/main/java/soma/haeya/edupi_user/login/dto/TokenInfo.java
  src/main/java/soma/haeya/edupi_user/login/service/MemberService.java
  src/test/java/soma/haeya/edupi_user/login/auth/TokenProviderTest.java
  src/test/java/soma/haeya/edupi_user/login/client/MemberApiClientTest.java
  src/test/java/soma/haeya/edupi_user/login/controller/MemberControllerTest.java
  src/test/java/soma/haeya/edupi_user/login/service/MemberServiceTest.java
Labels: feat, BE

#15 [#14]refactor: DB-server 호출할 때 Http Interface 이용하도록 변경
  src/main/java/soma/haeya/edupi_user/auth/TokenProvider.java
  src/main/java/soma/haeya/edupi_user/client/MemberApiClient.java
  src/main/java/soma/haeya/edupi_user/client/config/MemberApiRestClientConfig.java
  src/main/java/soma/haeya/edupi_user/controller/MemberController.java
  src/main/java/soma/haeya/edupi_user/domain/Member.java
  src/main/java/soma/haeya/edupi_user/domain/Role.java
  src/main/java/soma/haeya/edupi_user/dto/TokenInfo.java
  src/main/java/soma/haeya/edupi_user/dto/request/MemberLoginRequest.java
  src/main/java/soma/haeya/edupi_user/dto/request/SignupRequest.java
  src/main/java/soma/haeya/edupi_user/dto/response/Response.java
  src/main/java/soma/haeya/edupi_user/exception/DbValidException.java
  src/main/java/soma/haeya/edupi_user/exception/GlobalExceptionHandler.java
  src/main/java/soma/haeya/edupi_user/exception/UnexpectedServerException.java
  src/main/java/soma/haeya/edupi_user/login/client/MemberApiClient.java
  src/main/java/soma/haeya/edupi_user/login/client/config/MemberApiRestClientConfig.java
  src/main/java/soma/haeya/edupi_user/login/controller/MemberController.java
  src/main/java/soma/haeya/edupi_user/login/domain/Role.java
  src/main/java/soma/haeya/edupi_user/login/service/MemberService.java
  src/main/java/soma/haeya/edupi_user/service/MemberService.java
  src/main/java/soma/haeya/edupi_user/signup/SignUpController.java
  src/main/java/soma/haeya/edupi_user/signup/SignUpExceptionHandler.java
  src/main/java/soma/haeya/edupi_user/signup/dto/response/ErrorResponse.java
  src/main/java/soma/haeya/edupi_user/signup/dto/response/SuccessResponse.java
  src/main/java/soma/haeya/edupi_user/signup/exception/DbValidException.java
  src/test/java/soma/haeya/edupi_user/login/auth/TokenProviderTest.java
  src/test/java/soma/haeya/edupi_user/login/client/MemberApiClientTest.java
  src/test/java/soma/haeya/edupi_user/login/controller/MemberControllerTest.java
  src/test/java/soma/haeya/edupi_user/login/service/MemberServiceTest.java
  src/test/java/soma/haeya/edupi_user/signup/dto/request/SignupRequestTest.java
Labels: BE, refactor

#16 [#13]teat: 회원가입 로직 테스트 작성
  src/main/java/soma/haeya/edupi_user/service/MemberService.java
  src/test/java/soma/haeya/edupi_user/auth/TokenProviderTest.java
  src/test/java/soma/haeya/edupi_user/client/MemberApiClientTest.java
  src/test/java/soma/haeya/edupi_user/controller/MemberControllerTest.java
  src/test/java/soma/haeya/edupi_user/dto/request/SignupRequestTest.java
  src/test/java/soma/haeya/edupi_user/login/auth/TokenProviderTest.java
  src/test/java/soma/haeya/edupi_user/login/client/MemberApiClientTest.java
  src/test/java/soma/haeya/edupi_user/login/controller/MemberControllerTest.java
  src/test/java/soma/haeya/edupi_user/login/service/MemberServiceTest.java
  src/test/java/soma/haeya/edupi_user/service/MemberServiceTest.java
  src/test/java/soma/haeya/edupi_user/signup/SignUpControllerTest.java
  src/test/java/soma/haeya/edupi_user/signup/dto/request/SignupRequestTest.java
Labels: test, BE

#20 [#19]style: indent 적용 및 로그아웃 기능 구현
  src/main/java/soma/haeya/edupi_user/controller/MemberController.java
Labels: feat, BE
